import type { Metadata } from "next";
import "@/css/style.css";
import "@/css/satoshi.css";
import TanstackProvider from "@/provider/TanstackProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        suppressHydrationWarning={true}
      >
        <TanstackProvider>
            <div>
              {children}
            </div>
        </TanstackProvider>
      </body>
    </html>
  );
}
